services:
  - type: web
    name: scheduler-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SCHEDULER_API_KEY
        sync: false
      - key: SCHEDULER_API_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CONTACT_EMAIL
        sync: false
      - key: GMAIL_USER_1
        sync: false
      - key: GMAIL_PASS_1
        sync: false
      - key: GMAIL_USER_2
        sync: false
      - key: GMAIL_PASS_2
        sync: false
      - key: GMAIL_USER_3
        sync: false
      - key: GMAIL_PASS_3
        sync: false
      - key: ANALYTICS_PASSWORD_HASH
        sync: false
